config/routes.rb
Rails.application.routes.draw do
  resources :articles
  root 'pages#home'
  get 'about' => 'pages#about'
  get 'signup' => 'users#new'
  resources :users, except: [:new]

end

app/models/article.rb
class Article < ActiveRecord::Base
	belongs_to :user

	validates :title,       
						presence: true, 
						length: {minimum: 3 , maximum: 50}

	validates :description, 
						presence: true, 
						length: {minimum: 10, maximum: 300}
	validates :user_id,
						presence: true					
end

app/models/user.rb
class User < ActiveRecord::Base 
	has_many :articles
	before_save { self.email = email.downcase }
	validates :username, presence: true, 
											 uniqueness: { case_sensitive: false }, 
											 length: {minimum: 3, maximum: 15}

	VALID_EMAIL_REGEX = /\A([\w+\-]\.?)+@[a-z\d\-]+(\.[a-z]+)*\.[a-z]+\z/i
	validates :email,    presence: true, 
											 uniqueness: true, 
											 format: {with: VALID_EMAIL_REGEX }

	has_secure_password										 
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
	before_action :set_article, only: [:edit, :show, :update, :destroy]
	def index
		@articles = Article.paginate(page: params[:page], per_page: 3 )
	end

	def new
		@article = Article.new
	end 

	def edit
		
	end

	def create
		@article = Article.new(article_params)
		@article.user = User.first
		if @article.save
			flash[:notice] = "Article created"
			redirect_to article_path(@article)
		else
			render 'new'
		end	
	end
	
	def update
		if @article.update(article_params)
			flash[:notice] = "Article updated"
			redirect_to article_path(@article)
		else
			render 'edit'
		end
	end

	def show
		
	end

	def destroy
		if @article.destroy
			redirect_to articles_path
			flash[:notice] = "Article deleted"
		end
	end

	private 
	def set_article
		@article = Article.find(params[:id])
	end
	def article_params
		params.require(:article).permit(:title, :description)
	end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end

  def about
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
	before_action :set_user, only: [:edit, :update, :show]
	def index
		@users = User.paginate(page: params[:page], per_page: 3 )
	end

	def new
		@user = User.new
	end

	def create
		@user = User.new(user_params)
		if @user.save
			flash[:notice] = "Welcome to the blog #{@user.username}"
			redirect_to articles_path
		else
			render 'new'
		end	
	end
	
	def edit
		
	end

	def update
		if @user.update(user_params)
			flash[:notice] = "User updated"
			redirect_to articles_path
		else
			render 'edit'
		end
	end

	def show
		
	end

	private
	def set_user
		@user = User.find(params[:id])
	end
	def user_params
		params.require(:user).permit(:username, :email, :password)
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
	def gravatar_for(user)
		gravatar_id = Digest::MD5::hexdigest(user.email.downcase)
		gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}"
		image_tag(gravatar_url, alt: user.username, class: "img-circle")
	end
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/articles/_form.html.erb
<% if @article.errors.any? %>
<div class="row">
<div class="col-xs-8 col-xs-offset-2">
	<div class="alert alert-danger" role="alert">
	<ul>
		<% @article.errors.full_messages.each do |msg| %>
			<li><%= msg %></li>
		<% end %>
	</ul>
	</div>
</div>

</div>
	
<% end %>
<div class="row">
	<div class="col-sm-10 col-sm-offset-1">
		<%= form_for @article do |f| %>
			<div class="form-group">
				<%= f.label :title %>
				<%= f.text_field :title, class: "form-control", autofocus: true, placeholder: "Title of article" %><br>
			</div>
			<div class="form-group">
				<%= f.label :description %>
				<%= f.text_area :description, class: "form-control", placeholder: "Content of the article", rows: 10  %><br>
			</div>
			<%= f.submit class: "btn btn-info" %>  <%= link_to 'back', articles_path, class: "btn btn-default btn-sm" %>
	<% end %>
	</div>
</div>

	

app/views/articles/edit.html.erb
<div class="center">
	<h1>Edit article</h1>
</div>


<%= render 'form' %>

app/views/articles/index.html.erb
<h1 class="text-center">Listing all articles</h1>
<div align="center" >
	<%= will_paginate %>
</div>
	<div class="row">
		<div class="col-xs-8 col-xs-offset-2">
		<% @articles.each do |article| %>
			<div class="panel panel-primary ">
				<div class="panel-heading">
					<h3 class="panel-title">Title: <%= article.title %></h3>
				</div>
				<div class="panel-body">
    			<%= article.description %>
    			<div class="article-details">
	    				<small><i class="fa fa-user" aria-hidden="true"></i>  
	    						<%= article.user.username if article.user %> 
	    						<i class="fa fa-clock-o" aria-hidden="true"></i> 
	    						<%= time_ago_in_words(article.created_at) %> ago, 
	    				</small> 
    			</div>
  			</div>
  			<div class="panel-footer">
  				<%= link_to 'edit', edit_article_path(article), class: "btn btn-warning btn-xs " %>
					<%= link_to 'show', article, class: "btn btn-info btn-xs" %>
					<%= link_to 'delete', article, method: :delete, data: {confirm: "Are you sure?"}, class: "btn btn-danger btn-xs" %>
  			</div>
					
			</div>
			<% end %>
			<%= link_to 'new article', new_article_path, class: "btn btn-default btn-sm"%>
		</div>
	</div>
			
	<div align="center" >
	<%= will_paginate %>
</div>

app/views/articles/new.html.erb
<h1 class="center" >Create an article</h1>

<%= render 'form'%>
<div id="margin-bottom"></div>

app/views/articles/show.html.erb
<h2 align="center">Title: <%= @article.title %></h2>
<div class="well col-xs-8 col-xs-offset-2">
	<h4 class="center" ><strong>Description:</strong></h4>
	<hr>
	 <%= simple_format(@article.description) %><br>
	 <hr>
	 <%= link_to 'back', articles_path , class: "btn btn-default btn-sm"%> 
	<%= link_to 'Edit this article', edit_article_path , class: "btn btn-default btn-sm"%> 
	<%= link_to 'new article', new_article_path, class: "btn btn-default btn-sm" %> 
</div>

 

	

app/views/layouts/_footer.html.erb
<div class="navbar-static-bottom">
	<footer class="footer-distributed">

			<div class="footer-right">

				<a href="#"><i class="fa fa-facebook"></i></a>
				<a href="#"><i class="fa fa-twitter"></i></a>
				<a href="#"><i class="fa fa-linkedin"></i></a>
				<a href="#"><i class="fa fa-github"></i></a>

			</div>

			<div class="footer-left">

				<p class="footer-links">
					<a href="#">Home</a>
					·
					<%= link_to 'Articles', articles_path %>
					·
					<a href="#">About</a>
					·
					<a href="#">Contact</a>
				</p>

				<p>Victor Zerefos &copy; 2016</p>
			</div>

		</footer>
</div>

app/views/layouts/_messages.html.erb
<div class="row">
<div class="col-xs-10 col-xs-offset-1">
<% flash.each do |name, msg| %>
	<div class="alert alert-success" role="alert">
		<ul>
		<li><%= msg %></li>
	</ul>

	</div>
<% end %>

</div>

</div>



	

app/views/layouts/_navigation.html.erb
<!-- static navbar -->
    <nav class="navbar navbar-inverse navbar-fixed-top">
      <div class="container">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
           <%= link_to 'alpha blog', root_path, class:"navbar-brand", id: "logo" %>
        </div>
        <div id="navbar" class="navbar-collapse collapse">
          <ul class="nav navbar-nav navbar-right">
            <li><%= link_to 'Articles', articles_path %></li>
            <li><a href="#about">About</a></li>
            <li><a href="#contact">Contact</a></li>
            <li class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Dropdown <span class="caret"></span></a>
              <ul class="dropdown-menu">
                <li><%= link_to 'Create Article', new_article_path %></li>
                <li><a href="#">Another action</a></li>
                <li><a href="#">Something else here</a></li>
                <li role="separator" class="divider"></li>
                <li class="dropdown-header">Nav header</li>
                <li><a href="#">Separated link</a></li>
                <li><a href="#">One more separated link</a></li>
              </ul>
            </li>
          </ul>
        </div><!--/.nav-collapse -->
      </div>
    </nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>AlphaBlog</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
 
 		<%= render 'layouts/navigation'%>

	<div class="container">
		<%= render 'layouts/messages' %>
		<%= yield %>
	</div>

		<%= render 'layouts/footer'%>
</body>
</html>

app/views/pages/about.html.erb
<h1>Pages#about</h1>
<%= link_to 'Home', root_path %>

app/views/pages/home.html.erb
<div class="center jumbotron">
	<h1>Welcome to my Home Page</h1>
	<br>
	<div class="btn btn-info btn-lg">Sign Up</div>	
</div>

app/views/users/_form.html.erb
<% if @user.errors.any? %>
<div class="row">
<div class="col-xs-8 col-xs-offset-2">
	<div class="alert alert-danger" role="alert">
	<ul>
		<% @user.errors.full_messages.each do |msg| %>
			<li><%= msg %></li>
		<% end %>
	</ul>
	</div>
</div>

</div>
	
<% end %>
<div class="row">
	<div class="col-sm-10 col-sm-offset-1">
		<%= form_for @user do |f| %>
			<div class="form-group">
				<%= f.label :username %>
				<%= f.text_field :username, class: "form-control", autofocus: true, placeholder: "Enter username" %><br>
			</div>

			<div class="form-group">
				<%= f.label :email %>
				<%= f.email_field :email, class: "form-control", placeholder: "Enter email" %><br>
			</div>

			<div class="form-group">
				<%= f.label :password %>
				<%= f.password_field :password, class: "form-control", autofocus: true, placeholder: "Enter password" %><br>
			</div>
			<%= f.submit(@user.new_record? ? "Sign Up" : "Update User" ,  class: "btn btn-info") %>
	<% end %>
	</div>
	<div class="col-sm-4 col-sm-offset-4" >
		[<%= link_to 'Cancel request and return to articles listing', articles_path %>]
	</div>
</div>

	

app/views/users/edit.html.erb
<div class="center">
	<h1>Edit User</h1>
</div>


<%= render 'form' %>

app/views/users/index.html.erb
<h1 align="center" >Users Listing</h1>

	<%= will_paginate %>

<div class="row">
		<div class="col-xs-8 col-xs-offset-2">
		<% @users.each do |user| %>
			<div class="panel panel-primary ">
				<div class="panel-heading">
					<h3 class="panel-title">Username: <%= link_to user.username, user_path(user)%></h3>
				</div>
				<div class="panel-body">
    			<%= pluralize(user.articles.count, "article") if user.articles %>
  			</div>
  			<div class="panel-footer">
  				<%= link_to 'edit', edit_user_path(user), class: "btn btn-warning btn-xs " %>
					<%= link_to 'show', user, class: "btn btn-info btn-xs" %>
					<%= link_to 'delete User', user, method: :delete, data: {confirm: "Are you sure?"}, class: "btn btn-danger btn-xs" %>
  			</div>
					
			</div>
			<% end %>
			<%= link_to 'new user', signup_path, class: "btn btn-default btn-sm"%>
		</div>
		<%= will_paginate %>
	</div>

app/views/users/new.html.erb
<h1 class="text-center" >User Sign Up</h1>
<% if @user.errors.any? %>
<div class="row">
<div class="col-xs-8 col-xs-offset-2">
	<div class="alert alert-danger" role="alert">
	<ul>
		<% @user.errors.full_messages.each do |msg| %>
			<li><%= msg %></li>
		<% end %>
	</ul>
	</div>
</div>

</div>
	
<% end %>
<div class="row">
	<div class="col-sm-10 col-sm-offset-1">
		<%= form_for @user do |f| %>
			<div class="form-group">
				<%= f.label :username %>
				<%= f.text_field :username, class: "form-control", autofocus: true, placeholder: "Enter username" %><br>
			</div>

			<div class="form-group">
				<%= f.label :email %>
				<%= f.email_field :email, class: "form-control", placeholder: "Enter email" %><br>
			</div>

			<div class="form-group">
				<%= f.label :password %>
				<%= f.password_field :password, class: "form-control", autofocus: true, placeholder: "Enter password" %><br>
			</div>
			<%= f.submit 'Sign Up', class: "btn btn-info" %>
	<% end %>
	</div>
	<div class="col-sm-4 col-sm-offset-4" >
		[<%= link_to 'Cancel request and return to articles listing', articles_path %>]
	</div>
</div>

	

app/views/users/show.html.erb
<h2 align="center">Welcome <%= @user.username %></h2>

<div class="row">
		<div align="center" class="col-xs-4 col-xs-offset-4">
			 <%= gravatar_for @user%>
				<h4 align="center" ><%= @user.username %>' articles</h4>
		</div>
</div>

<div class="col-xs-8 col-xs-offset-2">
			 <% @user.articles.each do |ua|  %>
					<div class="panel panel-primary ">

							<div class="panel-heading">
								<h3 class="panel-title">Title: <%= ua.title %></h3>
								<small>Created: <%= time_ago_in_words(ua.created_at) %> ago.</small>
							</div>

							<div class="panel-body">
			    			<%= ua.description %><br>
			    	
			  			</div>	

			  			<div class="panel-footer">
			  				<%= link_to 'edit', edit_article_path(ua), class: "btn btn-warning btn-xs " %>
								<%= link_to 'delete Article', article_path(ua), method: :delete, data: {confirm: "Are you sure?"}, class: "btn btn-danger btn-xs" %>
	  					</div>

					</div>
			<% end %>		
</div>